services:
  qdrant:
    image: qdrant/qdrant:latest
    expose:
      - 6333
      - 6334
    ports:
      - "6334:6334"
      - "6333:6333"
    volumes:
      - storage:/qdrant:rw
  app:
    build: "."
    ports:
      - "8502:8501"

volumes:
  storage:
    