services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6334:6334"
      - "6333:6333"
    volumes:
      - storage:/qdrant:rw
  app:
    build: "."
    ports:
      - "8501:8501"

volumes:
  storage:
    